name: Deploy Game of life 

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: 
  
jobs:
  build_deploy_golife:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # AdoptOpenJDK successor
          java-version: '8'

      - name: Install Maven
        run: |
          sudo yum install maven -y


      # Step 3: Cache Maven dependencies 
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test
      - name: Build with Maven
        run: mvn clean install


      - name: Deploy WAR to Tomcat
        run: |
              WAR_FILE=$(ls gameoflife-web/target/*.war | head -n 1)
              APP_NAME=gameoflife
              curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
                --upload-file "$WAR_FILE" \
                "http://${{ secrets.TOMCAT_HOST }}:8081/manager/text/deploy?path=/$APP_NAME&update=true"
